# name: CI
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
# jobs:
#   build:
#     runs-on: [self-hosted, macos]
# #     defaults:
# #       run:
# #         shell: pwsh 
# #         working-directory: foo
#     steps:
#     - uses: actions/checkout@v2
#     - run: echo ::set-env name=foo::this is foo 1
#     - run: echo current env.foo ${{ env.foo }}
#     - name: TESTING
#       id: composite1
#       uses: ethanchewy/test-composite@outputs4
#       with:
#         your_name: "Octocat"
#       env:
#         foo: this is foo 2
# #       timeout-minutes: 1
# #     - run: dir
# #       if: always()
#     - name: test outputs
#       run: | 
#         echo test outputs random: ${{ steps.composite1.outputs.random_number}} 
#         echo test outputs food: ${{ steps.composite1.outputs.food}} 
# #     - run: echo current env.foo ${{ env.foo }}

# name: CI
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
# env:
#   TESTING_COMPOSITE_ACTIONS_ALPHA: 1
# jobs:
#   testing:
#     container:
#       image: alpine:latest
#     runs-on: [self-hosted, linux]
#     steps:
#       - uses: actions/checkout@v2
#       - id: composite1
#         uses: ethanchewy/test-script@container

# name: CI
# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
# jobs:
#   build:
#     runs-on: [self-hosted, macos]
#     steps:
#     - uses: actions/checkout@v2
#     - run: echo ::set-env name=foo::this is foo 1
#     - run: echo current env.foo ${{ env.foo }}
#     - id: composite1
#       uses: ethanchewy/test-composite@composing3
#       with:
#         your_name: "Octocat"
#       env:
#         foo: this is foo 2


name: Experiment

on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - uses: ethanchewy/include-workflow@test2
      with:
        workflow-steps: $GITHUB_WORKSPACE/.github/workflows/shared/snippet.yml
