# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  NAME1: test1
  NAME3: test3
  SERVER: production

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    
    
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - uses: ethanchewy/test-composite@v11
      with:
        your_name: "Octocat"
      env:
        NAME3: test31
      
    # Runs a single command using the runners shell
    - name: step 1
      run: echo Workflow step 1

    # Runs a set of commands using the runners shell
    - name: step 2
      run: echo Workflow step 2
    
    - name: environment tests
      run: |
        echo Server $SERVER
        echo Name1 $NAME1
        echo Name3 $NAME3
