name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  NAME1: test1
  NAME3: test3
  SERVER: production
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - id: composite
      uses: ethanchewy/test-composite@v16
      with:
        your_name: "Octocat"
      env:
        NAME3: testasdfasdfads
    - run: random number ${{ composite.outputs.random-number }}
    - name: step 1
      run: echo Workflow step 1
    - name: step 2
      run: echo Workflow step 2
    - run: |
        echo Workflow
        echo Server $SERVER
        echo Name1 $NAME1
        echo Name3 $NAME3
    - run: echo Workflow ${{env.NAME3}}
