name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: windows-latest
#     defaults:
#       run:
#         shell: pwsh 
#         working-directory: foo
    steps:
    - uses: actions/checkout@v2
#     - run: echo ::set-env name=foo::this is foo 1
#     - run: echo current env.foo ${{ env.foo }}
    - id: composite1
      uses: ethanchewy/test-script@v18
      env:
        TESTING_COMPOSITE_ACTIONS_ALPHA: 1
