name: CI
on: push
env:
  TESTING_COMPOSITE_ACTIONS_ALPHA: 1

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: ethanchewy/setup-runner@v1
        with:
          ref: ethanchewy/compositeScript
          token: ${{ secrets.RUNNER_TOKEN }}
